# Generated by Django 4.2.4 on 2023-10-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_posts_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='header_photo',
            field=models.ImageField(default='../media/images/default_profile.png', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='caption',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
