# Generated by Django 4.2.4 on 2023-09-18 10:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_userfollowing_unique_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='no_of_likes',
        ),
        migrations.AddField(
            model_name='posts',
            name='likes',
            field=models.ManyToManyField(related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
